version: '3.8'
services:

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - optimove

  postgre:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=OptiMoVe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

  optimove:
    build: 
      context: .
    volumes:
      - ./:/web_map
    expose:
      - 8000
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - DB_HOST=postgre
      - DB_NAME=OptiMoVe
      - DB_USER=postgres
      - DB_PASS=postgres
    env_file:
      - ./.env.dev
    depends_on:
      postgre:
        condition: service_healthy
