# Generated by Django 5.0.4 on 2024-05-13 17:09

from django.db import migrations


def CreateSuperUser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create_superuser(
        username="admin",
        password="admin",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(CreateSuperUser, reverse_code=lambda apps, schema_editor: None)
    ]
