# Generated by Django 4.2.6 on 2023-10-08 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.SmallIntegerField(verbose_name='Регион')),
                ('name', models.CharField(max_length=250, verbose_name='Название города')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название типа транспортного средства')),
                ('capacity', models.SmallIntegerField(verbose_name='Вместимость')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название маршрута')),
                ('interval', models.SmallIntegerField(verbose_name='Интервал движения')),
                ('amount', models.SmallIntegerField(verbose_name='Количество транспорта на маршруте')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetriNET.city', verbose_name='Город')),
                ('tc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PetriNET.tc', verbose_name='Тип транспортного средства')),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название остановки')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetriNET.city', verbose_name='Город')),
            ],
        ),
    ]
