# Generated by Django 4.2.6 on 2023-10-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstop',
            options={'verbose_name': 'Остановка', 'verbose_name_plural': 'Остановки'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='tc',
            options={'verbose_name': 'Тип транспортного средства', 'verbose_name_plural': 'Типы транспортных средств'},
        ),
        migrations.AlterField(
            model_name='busstop',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
