# Generated by Django 4.2.6 on 2023-10-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0002_alter_busstop_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='list_coord',
            field=models.JSONField(null=True, verbose_name='Порядок остановок'),
        ),
        migrations.AlterField(
            model_name='route',
            name='amount',
            field=models.SmallIntegerField(null=True, verbose_name='Количество транспорта на маршруте'),
        ),
        migrations.AlterField(
            model_name='route',
            name='interval',
            field=models.SmallIntegerField(null=True, verbose_name='Интервал движения'),
        ),
    ]
