# Generated by Django 4.2.6 on 2023-10-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0003_route_list_coord_alter_route_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='busstop',
            field=models.ManyToManyField(to='PetriNET.busstop', verbose_name='Остановки'),
        ),
    ]
