# Generated by Django 4.2.6 on 2023-12-20 20:04

import PetriNET.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0004_route_busstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='EI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название единицы измерения')),
                ('short_name', models.CharField(max_length=15, verbose_name='Краткое название')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.AlterField(
            model_name='busstop',
            name='latitude',
            field=models.FloatField(validators=[PetriNET.models.validate_latitude], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='longitude',
            field=models.FloatField(validators=[PetriNET.models.validate_longitude], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(validators=[PetriNET.models.validate_latitude], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(validators=[PetriNET.models.validate_longitude], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
