# Generated by Django 4.2.1 on 2024-03-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0005_ei_alter_busstop_latitude_alter_busstop_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='list_coord',
            field=models.JSONField(null=True, verbose_name='Список координат, по которым проходит маршрут'),
        ),
        migrations.AddIndex(
            model_name='busstop',
            index=models.Index(fields=['latitude', 'longitude'], name='PetriNET_bu_latitud_9d6742_idx'),
        ),
    ]
