# Generated by Django 4.1.7 on 2024-03-30 20:05

from django.db import migrations, models


# def CreateFirstCity(apps, schema_editor):
#     City = apps.get_model('PetriNET', 'City')
#     City.objects.create(name='Оренбург', latitude=51.7727, longitude=55.0988)


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0006_alter_route_list_coord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='interval',
            field=models.SmallIntegerField(default=5, verbose_name='Интервал движения в минутах'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        # migrations.RunPython(CreateFirstCity, reverse_code=lambda apps, schema_editor: None)
    ]
