# Generated by Django 5.0.4 on 2024-05-13 17:22
from django.core.management import call_command
from django.db import migrations


def start_add_citys(apps, schema_editor):
    call_command('add_citys')


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0008_remove_city_region'),
    ]

    operations = [
        migrations.RunPython(start_add_citys, reverse_code=lambda apps, schema_editor: None)
    ]
