# Generated by Django 5.0.4 on 2024-05-13 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0009_add_citys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=9, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота'),
        ),
    ]
