# Generated by Django 5.1.7 on 2025-09-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0011_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='list_coord_to_render',
            field=models.JSONField(null=True, verbose_name='Список координат для рендеринга'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название типа транспортного средства'),
        ),
    ]
