# Generated by Django 5.1.7 on 2025-09-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0012_route_list_coord_to_render_alter_tc_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together={('latitude', 'longitude')},
        ),
    ]
