# Generated by Django 5.1.7 on 2025-09-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0013_alter_busstop_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('input_data', models.JSONField(help_text='Данные маршрутов, остановок и параметров, переданные для расчёта', verbose_name='Входные данные для расчёта')),
                ('report_data', models.JSONField(help_text='Обработанные данные для генерации отчёта', verbose_name='Данные для отчёта')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание симуляции', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Симуляция',
                'verbose_name_plural': 'Симуляции',
                'ordering': ['-created_at'],
            },
        ),
    ]
