# Generated by Django 5.1.7 on 2025-11-29 05:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0014_simulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название сценария')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сценария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_flows', to='PetriNET.city', verbose_name='Город')),
                ('routes', models.ManyToManyField(blank=True, help_text='Маршруты, участвующие в сценарии', related_name='passenger_flows', to='PetriNET.route', verbose_name='Маршруты')),
            ],
            options={
                'verbose_name': 'Сценарий пассажиропотока',
                'verbose_name_plural': 'Сценарии пассажиропотока',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassengerFlowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers_count', models.PositiveIntegerField(help_text='Количество людей, следующих по данному направлению', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество пассажиров')),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_flow_from', to='PetriNET.busstop', verbose_name='Остановка отправления')),
                ('passenger_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='PetriNET.passengerflow', verbose_name='Сценарий пассажиропотока')),
                ('to_stop', models.ForeignKey(blank=True, help_text='Если не указано, пассажиры распределяются по маршруту', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_flow_to', to='PetriNET.busstop', verbose_name='Остановка назначения')),
            ],
            options={
                'verbose_name': 'Запись пассажиропотока',
                'verbose_name_plural': 'Записи пассажиропотока',
                'ordering': ['from_stop__name'],
            },
        ),
    ]
