# Generated by Django 5.1.7 on 2025-12-01 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetriNET', '0015_passengerflow_passengerflowentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='amount',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество транспорта должно быть не менее 1')], verbose_name='Количество транспорта на маршруте'),
        ),
        migrations.AlterField(
            model_name='route',
            name='interval',
            field=models.SmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1, message='Интервал движения должен быть не менее 1 минуты')], verbose_name='Интервал движения в минутах'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='capacity',
            field=models.SmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1, message='Вместимость должна быть не менее 1')], verbose_name='Вместимость'),
        ),
    ]
